name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        name: Release Please
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  config-file: .release-please-config.json
                  manifest-file: .release-please-manifest.json

    install:
        name: Install dependencies
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        runs-on: ubuntu-latest
        outputs:
            cache-hit: ${{ steps.pnpm-cache.outputs.cache-hit }}
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Cache pnpm dependencies
              id: pnpm-cache
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ env.STORE_PATH }}
                      node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              if: steps.pnpm-cache.outputs.cache-hit != 'true'
              run: pnpm install

    build:
        name: Build
        needs: install
        if: ${{ needs.release-please.outputs.release_created }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Restore pnpm dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ env.STORE_PATH }}
                      node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Cache build output
              id: build-cache
              uses: actions/cache@v4
              with:
                  path: |
                      dist
                      lib
                      build
                  key: ${{ runner.os }}-build-${{ hashFiles('src/**/*.ts', 'tsconfig.json') }}

            - name: Build
              if: steps.build-cache.outputs.cache-hit != 'true'
              run: pnpm build

    test:
        name: Unit Tests
        needs: [release-please, build]
        if: ${{ needs.release-please.outputs.release_created }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Restore pnpm dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ env.STORE_PATH }}
                      node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Restore build output
              uses: actions/cache@v4
              with:
                  path: |
                      dist
                      lib
                      build
                  key: ${{ runner.os }}-build-${{ hashFiles('src/**/*.ts', 'tsconfig.json') }}

            - name: Run tests
              run: pnpm test

    publish:
        name: Publish
        needs: [release-please, test]
        if: ${{ needs.release-please.outputs.release_created }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v5
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v4

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Restore pnpm dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ env.STORE_PATH }}
                      node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Restore build output
              uses: actions/cache@v4
              with:
                  path: |
                      dist
                      lib
                      build
                  key: ${{ runner.os }}-build-${{ hashFiles('src/**/*.ts', 'tsconfig.json') }}

            - name: Publish to NPM
              run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
